### PR TITLE
feat: search text

### PR DESCRIPTION
**Pull request by muskaanshah**
Features added -
search functionality implemented on enter
loaders
alerts

### CODE REVIEW

**Review by ScoobyDubeyDo — APPROVED** [review]
- feature working as expected
- Easy to understand
- Clean File structure
- Dividing the code into multiple components

**Review by Nishant-96 — APPROVED** [review]
Looks good to merge.
- Liked your Color Scheme
- Easily understandable code.

**Review by ayush65 — APPROVED** [review]
Code looks clean 
Good File structure 
Functionality working as expected

**Review by anuj-kumary — APPROVED** [review]
- Clean and modular code
- Functionality working as expected
- Good to merge

**Pull request merged**
